AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - config.ru
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/system/**
