require:
  rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - config/**/*
    - config.ru
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/models/**
    - spec/system/**

Rails/I18nLocaleTexts:
  Enabled: false
