# fly.toml app configuration file generated for circlecast on 2023-11-07T13:22:47+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "circlecast"
primary_region = "nrt"
console_command = "/rails/bin/rails console"
swap_size_mb = 512

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
